### ISSUE TITLE
Issue with apostrophe?

### ISSUE THREAD

**Issue by patrickvonplaten** [alvenirai/punctfix#13]
Hey :wave:,

This is a really user-friendly and nice package! Thanks a lot :-) 

I noticed that `punctfix` has some problems with apostrophe it seems. E.g.:

```python
>>> from punctfix import PunctFixer
>>> model = PunctFixer(language="en")

>>> example_text = "Let's go"
>>> print(model.punctuate(example_text))
```

doesn't seem to work as it gives:
```
AssertionError: Something went wrong due to handling of a long text... Tried matching the word: Let with Let's 
```

I'm running the following versions:
```
torch==1.13.1+cu116  
tokenizers==0.11.6
transformers==4.26.0
```

**Comment by sorenmulli** [comment]
Hey! Thank you for trying out this model and for helping us improve it by filing an issue.

As you write in https://github.com/huggingface/speechbox/issues/2, we only take raw text into consideration when reconstructing punctuation, so the model has been trained on text normalized to no punctuation. This was also assumed to be the case during inference which is the cause of the error.

We will fix this normalization upstream such that this should run without error.

-- Søren
